// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5OIE5aosX5kAUquq_kyGCccJiG23AWVo',
    appId: '1:278060018675:web:389379f0ea655ad2308086',
    messagingSenderId: '278060018675',
    projectId: 'appmusic-caa79',
    authDomain: 'appmusic-caa79.firebaseapp.com',
    databaseURL: 'https://appmusic-caa79-default-rtdb.firebaseio.com',
    storageBucket: 'appmusic-caa79.firebasestorage.app',
    measurementId: 'G-FVZZGZFNEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFbvK1xAhreXbP_xbDWroi2OagSuTuQeU',
    appId: '1:278060018675:android:e9291c733c383ca0308086',
    messagingSenderId: '278060018675',
    projectId: 'appmusic-caa79',
    databaseURL: 'https://appmusic-caa79-default-rtdb.firebaseio.com',
    storageBucket: 'appmusic-caa79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcLpBwI2aAd_YhiF1N_hnbvM0o-ETU_j0',
    appId: '1:278060018675:ios:36892cf49f75c63c308086',
    messagingSenderId: '278060018675',
    projectId: 'appmusic-caa79',
    databaseURL: 'https://appmusic-caa79-default-rtdb.firebaseio.com',
    storageBucket: 'appmusic-caa79.firebasestorage.app',
    iosBundleId: 'com.example.mainflutter',
  );
}
